name: Publish Docker Image
description: Build, Tag & Publish a Docker Image

inputs:
  registry:
    description: Registry URL
    required: true
  username:
    description: Registry username
    required: true
  password:
    description: Registry password
    required: true
  image:
    description: Name of the image
    required: true
  target:
    description: Dockerfile build target/stage to publish, also used as tag prefix
    required: true

runs:
  using: composite
  steps:
    - name: Authenticate with Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Extract Docker Metadata
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
        flavor: |
          latest=true
          prefix=${{ inputs.target }}-,onlatest=true

    - name: Build & Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        target: ${{ inputs.target }}
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        annotations: ${{ steps.metadata.outputs.annotations }}
