[program:laravel-pulse]
process_name=%(program_name)s
command=/opt/docker/bin/service.d/laravel-optional.sh laravel/pulse pulse:check
stopwaitsecs=3600

autostart=true
autorestart=true
user=application

stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

; This supresses supervisor (but not pulse) errors on stdout when the command fails
redirect_stderr=true
