name: Publish Docker Images

on:
  push:
    tags:
      - '*'
  workflow_dispatch: # Make this workflow runnable on github

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - test
    strategy:
      matrix:
        target: [ base, autopull, baked ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Authenticate with Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker Metadata
        id: metadata
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
          flavor: |
            latest=true
            prefix=${{ matrix.target }}-,onlatest=true

      - name: Build & Push Docker Image '${{ matrix.target }}'
        uses: docker/build-push-action@v7
        with:
          context: .
          target: ${{ matrix.target }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          annotations: ${{ steps.metadata.outputs.annotations }}
