name: Publish Docker Images

on:
  push:
    tags:
      - '*'
  workflow_dispatch: # Make this workflow runnable on github

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs:
      - test
    strategy:
      matrix:
        target: [ base, autopull, baked ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Publish Image '${{ matrix.target }}'
        uses: ./.github/actions/publish-image
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ github.repository_owner }}/laravel
          tag: ${{ matrix.target }}
          target: ${{ matrix.target }}
